### ISSUE TITLE
Can't connect to MongoDB after hosting on Heroku

### ISSUE THREAD

**Issue by MaxJeong** [beaucarnes/mern-exercise-tracker-mongodb#15]
It will only connect to the database if I run the nodemon command manually. How do I make the app connect automatically?

**Comment by aashimasingh** [comment]
I have the same issue! It only works on localhost. After deployment, it does not connect to MongoDB inspite of correct ATLAS_URI. I suspect it has something to do with axios.post, but I'm not sure what setting is missing :(

**Comment by MaxJeong** [comment]
I tried the following things:
- Updated server.js code that connects to mongodb
- Updated the backend's package.json to run a heroku postbuild script
- In Atlas's Network Access settings, I'm allowing all IP addresses to connect to the db
- In Heroku's settings, I put the ATLAS_URI as config var
- Tried to update the component's axios code but no luck

I think there is something wrong with axios code in general and the backend server is not running concurrently with the app.

**Comment by aashimasingh** [comment]
I tried the above too and it didn't work. What do you put in first argument of axion.post()? I had put 'http://localhost:5000' initially, but after deployment to Heroku, it expects a Heroku address.

**Comment by MaxJeong** [comment]
Yea I tried playing around with the Heroku address like putting herokulink/exercises and herokulink/users but no luck. And which axion.post() specifically? So far I've been trying to modify the get methods.

**Comment by aashimasingh** [comment]
I finally got it working on Heroku. const PORT = process.env.PORT || 5000; I had to set this in my server.js and I had initially used port and not PORT which was wrong I guess. I changed the main package.json to have these two commands:
"begin": "npm run build && node backend/server.js",
"start": "node backend/server.js && react-scripts start"
This makes the server and client run together. 
My app is a little different from the exercise tracker, instead of fetching data, it posts because of user subscription, hence the axion.post()
But I use the MERN stack exactly like this tutorial.

**Comment by MaxJeong** [comment]
Still doesn't work for me. I'm still getting the same error:

Failed to load resource: net::ERR_CONNECTION_REFUSED at localhost:5000/exercises/:1

Do you mind posting your version of the project to github? I want to see what your server.js and package.json look like as well as the components code.

**Comment by MaxJeong** [comment]
![rip](https://user-images.githubusercontent.com/8785918/77126927-17900180-6a21-11ea-88e3-46a1b99d3711.png)

I modified the correct package json this time and that is what I got. Error message:

Failed to load resource: the server responded with a status of 503 (Service Unavailable) at herokulink/:1

**Comment by aashimasingh** [comment]
My project is on a completely different topic, but you can check the server and package.json code on my github repo called kathak. It seems that you are trying to connect to localhost at port 5000, but heroku has its own port environment variable.

**Comment by MaxJeong** [comment]
What's your heroku port environment variable? And where can I find it? I defined the PORT variable correctly in server.js, like this:

const PORT = process.env.PORT || 5000;

I made both my package json files very similar to yours but I'm still getting that same 503 error. 

Can you take a look at my exercise-tracker project and see what's wrong?
